#!/bin/bash

echo "========================================"
echo "Rica Project Cleanup - Removing Unused Files"
echo "========================================"
echo ""

# Create a backup directory first
BACKUP_DIR="backup_$(date +%Y%m%d_%H%M%S)"
echo "Creating backup directory: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"

echo ""
echo "========================================"
echo "1. Removing Swarm/Browser-related files (feature removed)"
echo "========================================"
rm -f "SWARM_REDESIGN_SUMMARY.md"
rm -f "SWARM_QUICKSTART.md"
rm -f "SWARM_GOLOGIN_UI.md"
rm -f "SWARM_REMOVAL_SUMMARY.md"
echo "- Removed Swarm documentation files"

echo ""
echo "========================================"
echo "2. Removing OpenCTI/OpenBAS Docker files (integrated differently now)"
echo "========================================"
rm -f "docker-compose.openbas.yml"
rm -f "docker-compose.opencti.yml"
rm -f "fix-opencti-openbas.sh"
echo "- Removed OpenCTI/OpenBAS standalone compose files"

echo ""
echo "========================================"
echo "3. Removing duplicate/old Docker compose files"
echo "========================================"
rm -f "docker-compose.yml.new"
rm -f "docker-compose.simple.yml"
rm -f "docker-compose.yml"
echo "- Removed duplicate Docker compose files"

echo ""
echo "========================================"
echo "4. Removing old deployment scripts"
echo "========================================"
rm -f "deploy-simple.sh"
rm -f "deploy-landing.sh"
rm -f "deploy.bat"
rm -f "deploy.sh"
echo "- Removed old deployment scripts"

echo ""
echo "========================================"
echo "5. Removing redundant documentation"
echo "========================================"
# Keep the most comprehensive guides, remove duplicates
rm -f "DEPLOYMENT.md"
rm -f "PRODUCTION_GUIDE.md"
rm -f "QUICKSTART.md"
rm -f "QUICK_REFERENCE.md"
rm -f "QUICK_PORT_REFERENCE.md"
rm -f "OPENBAS_REMOVAL_SUMMARY.md"
rm -f "DOCKER_SETUP_SUMMARY.md"
rm -f "DEPLOYMENT_STATUS.md"
rm -f "FINAL_SUMMARY.md"
rm -f "IMPLEMENTATION_CHECKLIST.md"
rm -f "RICA_UI_READINESS_CHECKLIST.md"
echo "- Removed redundant documentation files"

echo ""
echo "========================================"
echo "6. Removing old setup scripts"
echo "========================================"
rm -f "setup.py"
rm -f "setup.bat"
rm -f "setup.sh"
rm -f "install.sh"
echo "- Removed old setup scripts"

echo ""
echo "========================================"
echo "7. Removing old update scripts"
echo "========================================"
rm -f "update-docker-compose.bat"
rm -f "update-docker-compose.sh"
rm -f "update-iframe-urls.bat"
rm -f "update-iframe-urls.sh"
echo "- Removed old update scripts"

echo ""
echo "========================================"
echo "8. Removing verification scripts (one-time use)"
echo "========================================"
rm -f "verify-removal.bat"
rm -f "verify-removal.sh"
echo "- Removed verification scripts"

echo ""
echo "========================================"
echo "9. Removing old nginx configs"
echo "========================================"
rm -f "rica.conf"
rm -f "headless-servers.conf"
echo "- Removed old nginx config files"

echo ""
echo "========================================"
echo "10. Removing old service files"
echo "========================================"
rm -f "rica.service"
echo "- Removed old systemd service file"

echo ""
echo "========================================"
echo "11. Removing empty/minimal package files"
echo "========================================"
rm -f "package-lock.json"
echo "- Removed empty package-lock.json"

echo ""
echo "========================================"
echo "12. Consolidating documentation"
echo "========================================"
# Move important docs to a docs folder for better organization
mkdir -p "docs"
mv -f "AUTHENTICATION_ARCHITECTURE.md" "docs/" 2>/dev/null
mv -f "MULTI_TENANCY_ARCHITECTURE.md" "docs/" 2>/dev/null
mv -f "RICA_ARCHITECTURE.md" "docs/" 2>/dev/null
mv -f "RESPONSIVE_DESIGN_GUIDE.md" "docs/" 2>/dev/null
mv -f "VISUAL_IMPROVEMENTS_GUIDE.md" "docs/" 2>/dev/null
mv -f "UI_ENHANCEMENTS_SUMMARY.md" "docs/" 2>/dev/null
mv -f "ENHANCED_COMPONENTS_SUMMARY.md" "docs/" 2>/dev/null
echo "- Organized architecture and design docs into docs/ folder"

echo ""
echo "========================================"
echo "Cleanup Summary"
echo "========================================"
echo "The following categories have been cleaned:"
echo "- Swarm/Browser feature files (removed feature)"
echo "- OpenCTI/OpenBAS standalone files (now integrated)"
echo "- Duplicate Docker compose files"
echo "- Old deployment scripts"
echo "- Redundant documentation"
echo "- Old setup and update scripts"
echo "- Verification scripts"
echo "- Old nginx configs"
echo "- Old service files"
echo "- Empty package files"
echo ""
echo "Important documentation has been organized into the docs/ folder"
echo ""
echo "========================================"
echo "Cleanup Complete!"
echo "========================================"
echo ""
echo "Remaining key files:"
echo "- docker-compose.prod.yml (main production compose)"
echo "- docker-compose.master.yml (master orchestration)"
echo "- docker-compose.headless-servers.yml (headless services)"
echo "- docker-compose.*.yml (individual service composes)"
echo "- start-rica-complete.bat/sh (main startup scripts)"
echo "- deploy-multi-tenancy.bat/sh (deployment scripts)"
echo "- README.md (main documentation)"
echo "- DEPLOYMENT_GUIDE.md (deployment guide)"
echo "- MULTI_TENANCY_GUIDE.md (multi-tenancy guide)"
echo "- PORT_MAPPING.md (port reference)"
echo ""
