version: '3.8'

# Docker Compose for Rica Core Services
# This file starts Rica UI (3030), Rica API (3001), and Rica Landing (3000)

services:
  # Rica API Service
  rica-api:
    build: 
      context: ./rica-api
      dockerfile: Dockerfile
    container_name: rica-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_EXTERNAL_URL=http://localhost:2022
      - API_KEY=${API_KEY:-changeme_in_production}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - ACTIVEPIECES_URL=http://activepieces:80
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Rica UI (Main Dashboard)
  rica-ui:
    build: 
      context: ./rica-ui
      dockerfile: Dockerfile
    container_name: rica-ui
    restart: unless-stopped
    ports:
      - "3030:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_RICA_UI_PORT=3030
      - REACT_APP_ACTIVEPIECES_URL=http://localhost:2020
      - REACT_APP_CODE_SERVER_URL=http://localhost:2021
      - REACT_APP_OLLAMA_URL=http://localhost:2022
    depends_on:
      - rica-api
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Rica Landing (Payment Portal)
  rica-landing:
    build:
      context: ./rica-landing
      dockerfile: Dockerfile
    container_name: rica-landing
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  rica-network:
    external: true
    name: rica-network
