version: '3.8'

services:
  # Rica UI
  rica-ui:
    build: 
      context: ./rica-ui
      dockerfile: Dockerfile
    container_name: rica-ui
    restart: always
    ports:
      - "3030:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_RICA_UI_PORT=3030
    depends_on:
      - rica-api
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Rica API Service
  rica-api:
    build: 
      context: ./rica-api
      dockerfile: Dockerfile
    container_name: rica-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_EXTERNAL_URL=http://localhost:2022
      - API_KEY=${API_KEY:-changeme_in_production}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - OPENCTI_URL=http://opencti:4000
      - OPENBAS_URL=http://openbas:3000
      - ACTIVEPIECES_URL=http://activepieces:80
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Rica Landing Page
  rica-landing:
    build:
      context: ./rica-landing
      dockerfile: Dockerfile
    container_name: rica-landing
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${LANDING_API_URL:-http://localhost:3001}
    volumes:
      - ./rica-landing/public:/usr/share/nginx/html:ro
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  rica-network:
    driver: bridge
