version: '3.8'

# PostgreSQL database for Rica authentication
# This file provides a standalone PostgreSQL instance for user authentication

services:
  postgres:
    image: postgres:15-alpine
    container_name: rica-auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_DB: rica_auth
      POSTGRES_MULTIPLE_DATABASES: rica_auth
    ports:
      - "5433:5432"
    volumes:
      - rica_auth_data:/var/lib/postgresql/data
      - ./init-auth.sql:/docker-entrypoint-initdb.d/init-auth.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rica-network

volumes:
  rica_auth_data:

networks:
  rica-network:
    external: true
    name: rica-network
