version: '3.8'

services:
  rica-ui:
    image: rica-ui:latest
    ports:
      - "${RICA_UI_PORT:-80}:80"
    environment:
      - API_BASE_URL=http://rica-api:${RICA_API_PORT:-3001}
    networks:
      - rica-network

  rica-api:
    image: rica-api:latest
    ports:
      - "${RICA_API_PORT:-3001}:3001"
    environment:
      - POSTGRES_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - rica-network

  firebase-sync:
    image: node:18
    volumes:
      - ./firebase-sync.js:/app/firebase-sync.js
    working_dir: /app
    command: node firebase-sync.js
    environment:
      - FIREBASE_ADMIN_CONFIG
      - PGPOOL_HOST=pgpool
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - pgpool
    networks:
      - rica-network

networks:
  rica-network:
    external: true
