version: '3.8'

services:
  # Rica UI
  rica-ui:
    build: 
      context: ./rica-ui
      dockerfile: Dockerfile
    container_name: rica-ui
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_AUTO_URL=http://localhost:2020
      - REACT_APP_CODE_SERVER_URL=http://localhost:2021
      - REACT_APP_OLLAMA_URL=http://localhost:2022
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Rica Landing Page
  rica-landing:
    build:
      context: ./rica-landing
      dockerfile: Dockerfile
    container_name: rica-landing
    restart: always
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3001
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rica-network:
    external: true
    name: rica-network
