version: '3.8'

services:
  # OpenCTI (Fabric)
  opencti:
    image: opencti/worker:5.12.12
    container_name: opencti
    restart: always
    ports:
      - "2020:4000"
    environment:
      - NODE_OPTIONS=--max_old_space_size=8192
      - APP__PORT=4000
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD:-ChangeMeInProduction123!}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN:-ChangeMeInProduction123!}
      - REDIS__HOSTNAME=redis
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=minio
      - MINIO__SECRET_KEY=${MINIO_SECRET_KEY:-miniokey}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=${RABBITMQ_PASSWORD:-guest}
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - rica-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: opencti-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-ChangeMeInProduction123!}
    volumes:
      - opencti_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - rica-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: opencti-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opencti_es_data:/usr/share/elasticsearch/data
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MinIO
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-50Z
    container_name: opencti-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-miniokey}
    volumes:
      - opencti_minio_data:/data
    networks:
      - rica-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: opencti-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - opencti_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  opencti_redis_data:
  opencti_es_data:
  opencti_minio_data:
  opencti_rabbitmq_data:

networks:
  rica-network:
    driver: bridge
