version: '3.8'

services:
  # Rica UI
  rica-ui:
    build:
      context: ./rica-ui
      dockerfile: Dockerfile
    container_name: rica-ui
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - rica-api
    networks:
      - rica-network

  # Rica API
  rica-api:
    build:
      context: ./rica-api
      dockerfile: Dockerfile
    container_name: rica-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
      - API_KEY=${API_KEY:-changeme_in_production}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
    depends_on:
      - ollama
    networks:
      - rica-network

  # Ollama (for DeepSeek)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rica-network

networks:
  rica-network:
    driver: bridge

volumes:
  ollama_data:
