version: '3.8'

services:
  # Code Server (VS Code in browser)
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    ports:
      - "2023:8080"
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD:-ChangeMeInProduction123!}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD:-ChangeMeInProduction123!}
      - DEFAULT_WORKSPACE=/home/coder/project
    volumes:
      - code_data:/home/coder
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rica-network

volumes:
  code_data:

networks:
  rica-network:
    driver: bridge
