version: '3.8'

services:
  # Ollama (for DeepSeek)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "2024:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - rica-network

volumes:
  ollama_data:

networks:
  rica-network:
    driver: bridge
