version: '3.8'

services:
  # Rica API Server
  rica-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rica-api-server:latest
    container_name: rica-api-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/rica
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - OPENCTI_URL=http://opencti:4000
      - OPENBAS_URL=http://openbas:3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo
    networks:
      - rica-network

  # MongoDB
  mongo:
    image: mongo:5.0
    container_name: rica-mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - rica-network

  # OpenCTI (optional - uncomment if you want to run OpenCTI in the same stack)
  # opencti:
  #   image: opencti/platform:latest
  #   container_name: rica-opencti
  #   restart: unless-stopped
  #   environment:
  #     - APP__PORT=4000
  #     - APP__ADMIN__EMAIL=admin@opencti.io
  #     - APP__ADMIN__PASSWORD=admin
  #     - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - rica-network

  # OpenBAS (optional - uncomment if you want to run OpenBAS in the same stack)
  # openbas:
  #   image: openbas/openbas:latest
  #   container_name: rica-openbas
  #   restart: unless-stopped
  #   environment:
  #     - APP__PORT=3000
  #     - APP__ADMIN__EMAIL=admin@openbas.io
  #     - APP__ADMIN__PASSWORD=admin
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - rica-network

volumes:
  mongo-data:

networks:
  rica-network:
    driver: bridge
