version: '3.8'

services:
  # Rica API Server
  rica-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rica-api-server:latest
    container_name: rica-api-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/rica
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - _URL=http://:4000
      - _URL=http://:3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo
    networks:
      - rica-network

  # MongoDB
  mongo:
    image: mongo:5.0
    container_name: rica-mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - rica-network

  #  (optional - uncomment if you want to run  in the same stack)
  # :
  #   image: /platform:latest
  #   container_name: rica-
  #   restart: unless-stopped
  #   environment:
  #     - APP__PORT=4000
  #     - APP__ADMIN__EMAIL=admin@.io
  #     - APP__ADMIN__PASSWORD=admin
  #     - APP__ADMIN__TOKEN=${_ADMIN_TOKEN}
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - rica-network

  #  (optional - uncomment if you want to run  in the same stack)
  # :
  #   image: /:latest
  #   container_name: rica-
  #   restart: unless-stopped
  #   environment:
  #     - APP__PORT=3000
  #     - APP__ADMIN__EMAIL=admin@.io
  #     - APP__ADMIN__PASSWORD=admin
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - rica-network

volumes:
  mongo-data:

networks:
  rica-network:
    driver: bridge
