version: '3.8'

services:
  # Rica Landing Page - Frontend
  rica-landing:
    build:
      context: .
      dockerfile: Dockerfile
    image: rica-landing:latest
    container_name: rica-landing
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
      # Firebase configuration
      - REACT_APP_FIREBASE_API_KEY=AIzaSyBm5gnFQofXAOCBpod4OQrwLWDrPy-OTzY
      - REACT_APP_FIREBASE_AUTH_DOMAIN=kelsoko-bddc4.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=kelsoko-bddc4
      - REACT_APP_FIREBASE_STORAGE_BUCKET=kelsoko-bddc4.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=605278507250
      - REACT_APP_FIREBASE_APP_ID=1:605278507250:web:1234567890abcdef
      # ClickPesa configuration
      - REACT_APP_CLICKPESA_API_KEY=${CLICKPESA_API_KEY}
      - REACT_APP_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # Analytics and monitoring
      - REACT_APP_ANALYTICS_KEY=${ANALYTICS_KEY}
      - REACT_APP_SENTRY_DSN=${SENTRY_DSN}
    networks:
      - rica-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/var/log/nginx
      - ./public/env.js:/usr/share/nginx/html/env.js:ro

networks:
  rica-network:
    driver: bridge
